### ISSUE TITLE
Blank... but with a bit more.

### ISSUE THREAD

**Issue by cfjedimaster** [phonegap/phonegap-template-blank#1]
I'd argue that "Blank" should contain just a tiny bit more than what is there now. Just one js file with the deviceready event listener and an empty handler. I'd think near 100% of apps will need this, and it would be a useful, and minimal, change.

**Comment by mwbrooks** [comment]
We spoke about this and the discussion is still open.

The problem with adding _just one js file_ is that everyone has different conventions - filenames and file paths. No matter what name or path we choose for the JavaScript file, most developers will have to delete, rename, or move the JavaScript file. That defeats the purpose of a blank project.

If we want to add `deviceready`, I'd suggest using a script tag in `index.html`. It's easy to remove and doesn't add to the file footprint.

**Comment by cfjedimaster** [comment]
Yeah, I see your point. I almost with the CLI would let me set a preference for --copy-from defaults so when I did cordova create X it would always use my preferred default. :)

**Comment by devgeeks** [comment]
This issues is over a year old. I think I am going to close it for now. 

The main rationale for me is that this needs to be blank enough for projects that use a module bundler like browserify or webpack, therefore adding _any_ JS files might be too many.
